include set
boost 1.81.0 requires set to be included directly:

  cd /var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2_build/src/common && /usr/sbin/x86_64-pc-linux-gnu-g++ -DAUTO_INITIALIZE_EASYLOGGINGPP -DBLOCKCHAIN_DB=DB_LMDB -DBOOST_ASIO_ENABLE_SEQUENTIAL_STRAND_ALLOCATION -DBUILD_TAG=amd64 -DDEFAULT_DB_TYPE=\"lmdb\" -DDEVICE_TREZOR_READY=1 -DHAVE_EXPLICIT_BZERO -DHAVE_HIDAPI -DHAVE_READLINE -DHAVE_STRPTIME -DHAVE_TREZOR_LIBUSB=1 -DPER_BLOCK_CHECKPOINT -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/external/rapidjson/include -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/external/easylogging++ -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/src -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/contrib/epee/include -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/external -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/external/supercop/include -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2_build/generated_include -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2_build/translations -I/var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/external/db_drivers/liblmdb -I/usr/include/hidapi -I/usr/include/libusb-1.0  -march=native -O2 -pipe -fomit-frame-pointer -DUSE_EXTRA_EC_CERT -pthread -maes -march=native -fno-strict-aliasing -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Wno-reorder -Wno-missing-field-initializers -fPIC  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fstack-clash-protection -Werror=switch -Werror=return-type -fno-strict-aliasing -ftemplate-depth=900 -DNDEBUG -Ofast  -std=c++14 -MD -MT src/common/CMakeFiles/obj_common.dir/dns_utils.cpp.o -MF CMakeFiles/obj_common.dir/dns_utils.cpp.o.d -o CMakeFiles/obj_common.dir/dns_utils.cpp.o -c /var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/src/common/dns_utils.cpp
  /var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/src/common/dns_utils.cpp: In function ‘bool tools::dns_utils::load_txt_records_from_dns(std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&)’:
  /var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/src/common/dns_utils.cpp:517:20: error: ‘set’ is not a member of ‘std’
    517 |   std::vector<std::set<std::string> > records;
        |                    ^~~
  /var/tmp/portage/net-p2p/monero-0.18.1.2/work/monero-0.18.1.2/src/common/dns_utils.cpp:39:1: note: ‘std::set’ is defined in header ‘<set>’; did you forget to ‘#include <set>’?
     38 | #include <boost/algorithm/string/join.hpp>
    +++ |+#include <set>
     39 | #include <boost/optional.hpp>