Another fix for building on OpenBSD
Instead of checking for HAVE_LIBRESSL in
external/unbound/sldns/keyraw.c, we check for LIBRESSL_VERSION_NUMBER.

This change resolves the following link errors on OpenBSD:
../../external/unbound/libunbound.a(keyraw.c.o): In function `sldns_key_buf2dsa_raw':
keyraw.c:(.text+0x1da): undefined reference to `DSA_set0_pqg'
keyraw.c:(.text+0x1f0): undefined reference to `DSA_set0_key'
../../external/unbound/libunbound.a(keyraw.c.o): In function `sldns_key_buf2rsa_raw':
keyraw.c:(.text+0x33d): undefined reference to `RSA_set0_key'