Fix:  error: value-initialization of incomplete type
https://github.com/monero-project/bitmonero/issues/834

Compilion bitmonero on Arch Linux (GCC 6.1) results in the following
error:

/home/mwo/bitmonero/src/crypto/crypto.cpp:275:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);

A proposed solution is to replace the line in question into:

return sizeof(rs_comm) + pubs_count * 2 * sizeof(ec_point);

Arch Linux just upgrade GCC 5.3 to 6.1. With this change, Monero no longer compiles. Compilation fails for the following errors: